### ISSUE TITLE
Could you please explain what's header info

### ISSUE THREAD

**Issue by Oymate** [remi0s/aosp-dictionary-tools#2]
I didn't understand from the README.md what header info is

**Comment by remi0s** [comment]
for example the included el_wordlist.combined contains the following head at the first line:
`dictionary=main:el,locale=el,description=Greek dict created from Wiki and OpenSubtitles by Rafail Mastoras,date=1542122459,version=1`
it is needed for the AOSP keyboard to recognize the keyboards locale and other info.
