### ISSUE TITLE
Unable to create dict file

### ISSUE THREAD

**Issue by shahzad1** [remi0s/aosp-dictionary-tools#5]
Hi, I've followed all the steps mentioned but not being able to create dict file. I've also got the wordlist file but don't know where I'm doing wrong. May be you should mention the file name with extension to be added in Step#3 (After the wordlist is created use the parser.pl with command perl parser.pl filename > newfilename)
Because when I follow above command, I got an error which says "perl is not recognized as external or internal command". Also, when I follow step#3, the created has 0 kb size and after running run.sh file, the file size of 0 kb remains same.
#PleaseHelp

**Comment by shahzad1** [comment]
After struggling of whole day, I'm going to close this issue with a helpful note for everybody who wants to create dictionary binary file.
No doubt the owner of this repo has done wonderful job but I think he needs to explain every step in little more details. For example:

- Step#3 won't work unless you install Perl in your PC(tested on windows)
- In order to run step#6, you need to install Java JDK, otherwise you'll get **javaNotFoundExeption** when you execute run.sh file
- After installing Java JDK, put all the files in C:\Program Files\Java\jdk1.8.0_73\bin (or where ever you've installed jdk), then execute run.sh file and make sure you've granted write permission.
- Best way to execute run.sh file is to install **Git** then in **bin** folder, right click anywhere and select **Git bash here** then execute a command **./run.sh**

**Comment by chanhbc** [comment]
Can you describe the steps from installation to creating the "*.dict" file?
